//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Castle.ActiveRecord.Linq")]
[assembly: AssemblyProduct("Castle.ActiveRecord.Linq")]
[assembly: AssemblyVersion("2.1.2.0")]
[assembly: AssemblyInformationalVersion("2.1.2.0")]
[assembly: AssemblyFileVersion("2.1.2.0")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]


